DROP TABLE IF EXISTS `member`;
CREATE TABLE `member` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '账号类型：0个人1公司',
  `username` varchar(30) NOT NULL DEFAULT '' COMMENT '用户名',
  `password` varchar(32) NOT NULL DEFAULT '' COMMENT '密码',
  `nickname` char(36) NOT NULL DEFAULT '' COMMENT '昵称',
  `realname` varchar(20) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `identitycard` varchar(18) NOT NULL DEFAULT '' COMMENT '身份证号',
  `mobile` varchar(30) NOT NULL DEFAULT '' COMMENT '手机号',
  `smacc` varchar(30) NOT NULL DEFAULT '' COMMENT '社交账号',
  `terminal` varchar(20) NOT NULL DEFAULT '' COMMENT '注册终端',
  `system` varchar(100) NOT NULL DEFAULT '' COMMENT '系统',
  `brand` varchar(100) NOT NULL DEFAULT '' COMMENT '品牌',
  `user_agent` varchar(255) NOT NULL DEFAULT '' COMMENT 'UA信息',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0禁用1正常',
  `createip` varchar(20) NOT NULL DEFAULT '' COMMENT '创建IP',
  `lastlogintime` int(10) NOT NULL DEFAULT '0' COMMENT '最后登陆时间',
  `lastloginip` char(16) NOT NULL DEFAULT '' COMMENT '最后登陆IP',
  `emailstatus` tinyint(1) NOT NULL DEFAULT '0' COMMENT '邮箱验证：0未验证1验证',
  `phonestatus` tinyint(1) NOT NULL DEFAULT '0' COMMENT '手机验证：0未验证1验证',
  `idstatus` tinyint(1) NOT NULL DEFAULT '0' COMMENT '身份证验证：0未验证1验证',
  `create_time` int(10) DEFAULT '0' COMMENT '注册时间',
  `update_time` int(10) DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `username` (`username`),
  KEY `mobile` (`mobile`),
  KEY `realname` (`realname`),
  KEY `identitycard` (`identitycard`),
  KEY `lastlogintime` (`lastlogintime`)
) ENGINE=MyISAM AUTO_INCREMENT=1000000 DEFAULT CHARSET=utf8 COMMENT='会员表';